### ISSUE TITLE
Release 2.0.1 to Pypi

### ISSUE THREAD

**Issue by skoczen** [firebase/firebase-token-generator-python#10]
Hey there,

Just a quick request that you release the version here on github (2.0.1) out to pypi.  Without it, this lib doesn't work on python 3.x because of the `basestring` bug.

Thanks!

-Steven

**Comment by skoczen** [comment]
Just a ping on this, in case people have the repo muted: @robertdimarco or @drtriumph or @gsoltis ?

Many thanks!

**Comment by robertdimarco** [comment]
Resolved, thanks for the heads up!
